import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Collaborators from "../components/Collaborators";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Stats from "../components/Stats";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Stats />
      <Collaborators mt="" />
    </div>
  );
}
