import Head from "next/head";
import DashboardHero from "../components/DashboardHero";
import Navbar from "../components/Navbar";
import Router from "next/router";
import {supabase} from "../utils/supabaseClient";
import {Box, Image} from "@chakra-ui/react"
import {useLayoutEffect, useState} from "react";

export default function Dashboard(props) {
    const [isLoading, setIsLoading] = useState(true)
    const [loggedIn, setLoggedIn] = useState(props.loggedIn)
    const [user, setUser] = useState(null)

    useLayoutEffect (() => {
        if (loggedIn === false) {
            Router.push('/login')
        }

        async function fetchData() {
            const {data, error} = await supabase
                .from('profiles')
                .select('name, email, university')
                .eq('id', supabase.auth.user().id)
                .limit(1)

            if (data.length === 0) {
                await Router.push('/profile')
            }

            if (error) {
                throw error
            } else {
                setUser(data[0])
                setIsLoading(false)
            }
        }

        if (loggedIn === true && user === null) {
            fetchData();
        }

    }, [loggedIn, user])

    function getUserData(key) {
        if (user !== undefined && user !== null) {
            return user[key]
        }

        return ''
    }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {isLoading ? <Box w="100%"><Image src="/LFload.gif" alt={'Loading....'}/></Box> :
            <>
            <Navbar loggedIn={loggedIn}/>
            <DashboardHero name={getUserData('name')} avatar={supabase.auth.user().user_metadata.avatar_url} university={getUserData('university')}/>
            </>}
    </div>
  );
}
