import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Collaborators from "../components/Collaborators";
import FAQ from "../components/FAQ";
import Hero from "../components/Hero";
import Leaderboard from "../components/Leaderboard";
import Navbar from "../components/Navbar";
import Stats from "../components/Stats";
import styles from "../styles/Home.module.css";

import { ApolloClient, InMemoryCache, gql, HttpLink } from "@apollo/client";

export default function Home({ stats }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Stats
        pullRequests={stats.pullRequests}
        stars={stats.stars}
        commits={stats.commits}
      />
      <Collaborators />
      <Leaderboard />
      <FAQ />
    </div>
  );
}

export async function getStaticProps() {
  const GITHUB_BASE_URL = "https://api.github.com/graphql";

  const httpLink = new HttpLink({
    uri: GITHUB_BASE_URL,
    headers: {
      authorization: `Bearer ${process.env.GITHUB_PERSONAL_ACCESS_TOKEN}`,
    },
  });

  const client = new ApolloClient({
    link: httpLink,
    cache: new InMemoryCache(),
  });
  const response = await client.query({
    query: gql`
      query {
        repository(name: "LearntoberFest", owner: "hackclubskcet") {
          stargazerCount

          pullRequests {
            totalCount
          }
          object(expression: "master") {
            ... on Commit {
              history {
                totalCount
              }
            }
          }
        }
      }
    `,
  });
  const data = {
    stars: response.data.repository.stargazerCount,
    pullRequests: response.data.repository.pullRequests.totalCount,
    commits: response.data.repository.object.history.totalCount,
  };
  return {
    props: {
      stats: data,
    },
  };
}
